version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    versioning-strategy: increase
    groups:
      internal-deps-minor-and-patch:
        applies-to: version-updates
        patterns:
          - '@alkem/*'
        update-types:
          - 'minor'
          - 'patch'
      external-deps-minor-and-patch:
        applies-to: version-updates
        patterns:
          - '*'
        exclude-patterns:
          - '@alkem/*'
        update-types:
          - 'minor'
          - 'patch'
